import '../styles/frensday.css';
import '../styles/ethdenver24.css';
import '../styles/generic.css';

import React from 'react';

// export const metadata = {
//     title: 'Next.js',
//     description: 'Generated by Next.js',
// };

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return <>{children}</>;
}
