import '../styles/frensday.css';
import '../styles/generic.css';

import React from 'react';

// export const metadata = {
//     title: 'Next.js',
//     description: 'Generated by Next.js',
// };

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
    params: { slug: string };
    searchParams: { event?: string; iykRef?: string };
}) {
    return (
        // <html lang="en">
        <div>{children}</div>
        // </html>
    );
}
