/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NameRouteRouteImport } from './routes/$name/route'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as NamesRouteImport } from './routes/names'
import { Route as PoolsRouteImport } from './routes/pools'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NameIndexRouteImport } from './routes/$name/index'
import { Route as NameEditRouteImport } from './routes/$name/edit'
import { Route as PoolPoolIdRouteImport } from './routes/pool.$poolId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NameRouteRoute = NameRouteRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const NamesRoute = NamesRouteImport.update({
  id: '/names',
  path: '/names',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsRoute = PoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NameIndexRoute = NameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NameRouteRoute,
} as any)
const NameEditRoute = NameEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => NameRouteRoute,
} as any)
const PoolPoolIdRoute = PoolPoolIdRouteImport.update({
  id: '/pool/$poolId',
  path: '/pool/$poolId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$name': typeof NameRouteRouteWithChildren
  '/activity': typeof ActivityRoute
  '/names': typeof NamesRoute
  '/pools': typeof PoolsRoute
  '/settings': typeof SettingsRoute
  '/$name/edit': typeof NameEditRoute
  '/pool/$poolId': typeof PoolPoolIdRoute
  '/$name/': typeof NameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/names': typeof NamesRoute
  '/pools': typeof PoolsRoute
  '/settings': typeof SettingsRoute
  '/$name/edit': typeof NameEditRoute
  '/pool/$poolId': typeof PoolPoolIdRoute
  '/$name': typeof NameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$name': typeof NameRouteRouteWithChildren
  '/activity': typeof ActivityRoute
  '/names': typeof NamesRoute
  '/pools': typeof PoolsRoute
  '/settings': typeof SettingsRoute
  '/$name/edit': typeof NameEditRoute
  '/pool/$poolId': typeof PoolPoolIdRoute
  '/$name/': typeof NameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$name'
    | '/activity'
    | '/names'
    | '/pools'
    | '/settings'
    | '/$name/edit'
    | '/pool/$poolId'
    | '/$name/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/names'
    | '/pools'
    | '/settings'
    | '/$name/edit'
    | '/pool/$poolId'
    | '/$name'
  id:
    | '__root__'
    | '/'
    | '/$name'
    | '/activity'
    | '/names'
    | '/pools'
    | '/settings'
    | '/$name/edit'
    | '/pool/$poolId'
    | '/$name/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NameRouteRoute: typeof NameRouteRouteWithChildren
  ActivityRoute: typeof ActivityRoute
  NamesRoute: typeof NamesRoute
  PoolsRoute: typeof PoolsRoute
  SettingsRoute: typeof SettingsRoute
  PoolPoolIdRoute: typeof PoolPoolIdRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$name': {
      id: '/$name'
      path: '/$name'
      fullPath: '/$name'
      preLoaderRoute: typeof NameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/names': {
      id: '/names'
      path: '/names'
      fullPath: '/names'
      preLoaderRoute: typeof NamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools': {
      id: '/pools'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof PoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$name/': {
      id: '/$name/'
      path: '/'
      fullPath: '/$name/'
      preLoaderRoute: typeof NameIndexRouteImport
      parentRoute: typeof NameRouteRoute
    }
    '/$name/edit': {
      id: '/$name/edit'
      path: '/edit'
      fullPath: '/$name/edit'
      preLoaderRoute: typeof NameEditRouteImport
      parentRoute: typeof NameRouteRoute
    }
    '/pool/$poolId': {
      id: '/pool/$poolId'
      path: '/pool/$poolId'
      fullPath: '/pool/$poolId'
      preLoaderRoute: typeof PoolPoolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NameRouteRouteChildren {
  NameEditRoute: typeof NameEditRoute
  NameIndexRoute: typeof NameIndexRoute
}

const NameRouteRouteChildren: NameRouteRouteChildren = {
  NameEditRoute: NameEditRoute,
  NameIndexRoute: NameIndexRoute,
}

const NameRouteRouteWithChildren = NameRouteRoute._addFileChildren(
  NameRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NameRouteRoute: NameRouteRouteWithChildren,
  ActivityRoute: ActivityRoute,
  NamesRoute: NamesRoute,
  PoolsRoute: PoolsRoute,
  SettingsRoute: SettingsRoute,
  PoolPoolIdRoute: PoolPoolIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
